### ISSUE TITLE
Sample crashes upon start

### ISSUE THREAD

**Issue by redbrain** [macabeus/react-gbajs#18] opened 2023-03-23 02:58 UTC
I'm guessing this is an issue with outdated dependencies. An update would be appreciated.

**Comment by macabeus** [comment] 2023-03-23 07:49
I just cloned the repository and followed the [readme](https://github.com/macabeus/react-gbajs#contribution), and it worked.
Can you write a step-by-step to reproduce the crash, please? Including the browser, OS, and ROM file.
<img width="468" alt="image" src="https://user-images.githubusercontent.com/9501115/227137010-e002733f-59f1-4e9a-a194-7520d78cb4b1.png">


Also, please, try loading the same ROM on http://endrift.github.io/gbajs/ and say here if it worked or not.

**Comment by macabeus** [comment] 2023-05-23 23:53
Closing because it's staled

**Closed by macabeus** 2023-05-23 23:53 UTC
